 This is a sample build configuration for C++ – Make.
# Only use spaces to indent your .yml configuration.
# -----
# You can use any Docker image from Docker Hub, or your own container registry, as your build environment.
image: gcc:6.1
pipelines:
  default:
    - step:
        script: # Modify the commands below to build your repository.
          - sudo apt install libmicrohttpd-dev libssl-dev cmake build-essential libhwloc-dev
          - mkdir xmr-stak/build
          - cd xmr-stak/build
          - cmake ..
